# Generated by Django 2.1.3 on 2018-11-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitReveal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_hash', models.CharField(max_length=64, unique=True)),
                ('player_hash', models.CharField(max_length=64, unique=True)),
                ('player_plaintext', models.TextField()),
                ('server_plaintext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_hash', models.CharField(max_length=64, unique=True)),
                ('player_hash', models.CharField(max_length=64, unique=True)),
                ('salt', models.CharField(max_length=64)),
                ('solution', models.IntegerField()),
            ],
        ),
    ]
