# Generated by Django 2.1.3 on 2018-11-19 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitReveal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_hash', models.CharField(max_length=64, unique=True)),
                ('player_hash', models.CharField(max_length=64, unique=True)),
                ('player_plaintext', models.TextField()),
                ('server_plaintext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=64, unique=True)),
                ('solution', models.IntegerField()),
                ('commit_reveal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.CommitReveal')),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guess', models.IntegerField()),
                ('clueNb', models.IntegerField()),
                ('clueNw', models.IntegerField()),
                ('proof', models.TextField(null=True)),
                ('public_signals', models.TextField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Game')),
            ],
        ),
    ]
